name: project_code_blue
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  number_pagination: ^1.1.6
  modal_bottom_sheet: ^3.0.0
  flutter_steps: ^1.0.5
  horizontal_stepper_flutter: ^1.0.3
  intl: ^0.20.2
  adaptive_action_sheet: ^2.0.4
  progress_stepper: ^3.1.0
  im_stepper: ^1.0.1+1
  file_picker: ^9.0.2
  path_provider: ^2.1.2
  url_launcher: ^6.3.1
  permission_handler: ^11.4.0
  easy_pie_chart: ^1.0.2
  card_swiper: ^3.0.1
  flutter_chartx: ^1.0.0-dev8
  syncfusion_flutter_calendar: ^29.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/mainPicture.jpg
    - assets/images/collectionManagerLogo.png
    - assets/images/powered-by.png
    - assets/images/icons/home.png
    - assets/images/icons/dashboard.png
    - assets/images/icons/onSiteJobs.png
    - assets/images/icons/onSiteApprovals.png
    - assets/images/icons/clientManagement.png
    - assets/images/icons/accounting.png
    - assets/images/icons/collectionReports.png
    - assets/images/icons/calendar.png
    - assets/images/icons/faq.png
    - assets/images/icons/sectionIcon.png
    - assets/images/icons/faq.png
    - assets/images/icons/splash_icon.png
    - assets/images/icons/poweredBy_SA_splash.png
    - assets/images/icons/splash_icon_double.png
    - assets/images/icons/Powered by 2.png
    - assets/images/icons/refresh_icon.png
    - assets/images/icons/newJob_icon.png
    - assets/images/icons/newCallOutJob_icon.png
    - assets/images/icons/threeDots.png
    - assets/images/icons/eye_icon.png
    - assets/images/icons/showAchieve.png
    - assets/images/icons/navigateLeft.png
    - assets/images/icons/navigateRight.png
    - assets/images/icons/reportingIcon.png
    - assets/images/icons/hideArchieve.png
    - assets/images/icons/document_icon.png
    - assets/images/icons/dafault_icon.png
    - assets/images/icons/profileIcon.png
    - assets/images/icons/locationIcon.png
    - assets/images/icons/print.png
    - assets/images/icons/dropDownIcon.png
    - assets/images/icons/icon_calendar.png
    - assets/images/icons/refreshIcon.png
    - assets/images/icons/newJobOpen.png
    - assets/images/icons/openInvoice.png
    - assets/images/icons/downloadInvoice.png
    - assets/images/icons/arrow_left.png
    - assets/images/icons/collectionManagerNotifications.png
    - assets/images/icons/notificationTile.png
    - assets/images/icons/deleteNotification.png
    - assets/images/icons/arrow_right.png
    - assets/images/icons/calendarDate.png
    - assets/images/icons/contractAchieveOpened.png
    - assets/images/icons/contractAchieveClosed.png
    - assets/images/icons/locationIcon2.png
    - assets/images/icons/excelExport.png
    - assets/images/icons/theClock.png
    - assets/images/icons/people.png
    - assets/images/icons/sent_by.png
    - assets/images/icons/sent_time.png
    - assets/images/icons/sendByCollector.png
    - assets/images/icons/date_calendar.png
    - assets/images/icons/download.png
    - assets/images/icons/newCalloutIcon.png
    - assets/images/icons/newCalloutOpen.png
    - assets/images/icons/testsProcessed.png
    - assets/images/icons/X.png
    - assets/images/icons/1.png
    - assets/images/icons/2.png
    - assets/images/icons/3.png
    - assets/images/icons/4.png
    - assets/images/icons/5.png
    - assets/images/icons/6.png
    - assets/images/icons/7.png
    - assets/images/icons/addButton.png
    - assets/images/icons/addDisabled.png
    - assets/images/icons/newLocation.png
    - assets/images/icons/onSiteApprovalVector.png
    - assets/images/icons/printIcon.png
    - assets/images/icons/siteContactSignature.png
    - assets/images/icons/collectorSignature.png
    - assets/images/icons/delete.png
    - assets/images/icons/searchIcon.png
    - assets/images/icons/newClient.png
    - assets/images/icons/newNoteAdd.png
    - assets/images/icons/newNote.png
    - assets/images/icons/changeLogOpened.png
    - assets/images/icons/uploadNew.png
    - assets/images/icons/changeLogClosed.png
    - assets/images/icons/onSiteJobsIcon.png
    - assets/images/icons/onSiteApprovalsIcon.png
    - assets/images/icons/clientManagementIcon.png
    - assets/images/icons/newJobIcon.png
    - assets/images/icons/successfullySent.png
    - assets/images/icons/errorSendingReport.png
    - assets/images/icons/OnsiteJobs/calander_icon.png
    - assets/images/icons/OnsiteJobs/time_icon.png
    - assets/images/icons/OnsiteJobs/duration_icon.png
    - assets/images/backgrounds/home-page-background.jpg
    - assets/images/bottomNavigationIcons/selectedIcons/dashboard_selected.png
    - assets/images/bottomNavigationIcons/selectedIcons/onsiteJobs_selected.png
    - assets/images/bottomNavigationIcons/selectedIcons/clientManagement_selected.png
    - assets/images/bottomNavigationIcons/selectedIcons/collectionReports_selected.png
    - assets/images/bottomNavigationIcons/selectedIcons/accounting_selected.png
    - assets/images/bottomNavigationIcons/selectedIcons/dashboardTrueColor.png
    - assets/images/bottomNavigationIcons/selectedIcons/jobsTrueColor.png
    - assets/images/bottomNavigationIcons/selectedIcons/dashboardTrueColor.png
    - assets/images/bottomNavigationIcons/selectedIcons/reportsTrueColor.png
    - assets/images/bottomNavigationIcons/selectedIcons/accountingTrueColor.png
    - assets/images/bottomNavigationIcons/selectedIcons/cmTrueColor.png
    - assets/images/bottomNavigationIcons/unselectedIcons/dashboard_unselected.png
    - assets/images/bottomNavigationIcons/unselectedIcons/onsiteJobs_unselected.png
    - assets/images/bottomNavigationIcons/unselectedIcons/clientManagement_unselected.png
    - assets/images/bottomNavigationIcons/unselectedIcons/collectionReports_unselected.png
    - assets/images/bottomNavigationIcons/unselectedIcons/accounting_unselected.png
    - assets/images/welcomeBackIcons/welcomeBack_dashboard.png
    - assets/images/welcomeBackIcons/welcomeBack_onSiteJobs.png
    - assets/images/welcomeBackIcons/welcomeBack_onSiteApprovals.png
    - assets/images/welcomeBackIcons/welcomeBack_clientManagement.png
    - assets/images/welcomeBackIcons/welcomeBack_accounting.png
    - assets/images/welcomeBackIcons/welcomeBack_collectionReports.png
    - assets/images/welcomeBackIcons/welcomeBack_collectorsCalendar.png
    - assets/images/welcomeBackIcons/welcomeBack_faq.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
